### ISSUE TITLE
Include with Kemalyst?

### ISSUE THREAD

**Issue by drujensen** [TechMagister/i18n.cr#1]
@TechMagister Would it be difficult to integrate this to Kemalyst?

**Comment by TechMagister** [comment]
It should be easy, I think it can be done in 2 ways : 
1) Adding a local_path and locale attribute to Kemalyst::Application do allow the configuration using config/application.cr and initialize I18n.init into the Application#start method

or better : 
2) Create a kemalyst-i18n project with a Handler that use config/i18n.cr for the configuration and that can in the same time set the locale based on the "Accept-Language" http header.

The second one is less intrusive obviously.

**Comment by TechMagister** [comment]
Well... awaiting for bug fix in the compiler https://github.com/crystal-lang/crystal/issues/3691

**Comment by TechMagister** [comment]
Here it is : https://github.com/TechMagister/kemalyst-i18n

**Comment by drujensen** [comment]
Awesome!  :+1:
