### ISSUE TITLE
Translate not working

### ISSUE THREAD

**Issue by kingsleyh** [TechMagister/i18n.cr#14]
Hi

What does it mean when I get this instead of the expected translation?

```
KeyError:Missing hash key: "en"
```

I have done this:
```
I18n.load_path += ["#{__DIR__}/../../locales/**/*.yml"]
I18n.init
I18n.default_locale = "en"

I18n.translate("cli.wallet.title")
```

**Comment by kingsleyh** [comment]
ah I found the issue:

it appears that the glob style functionality doesn't work: `**/*.yml` and instead I had to specify each subfolder explicitly like this:  

```
I18n.load_path += ["#{__DIR__}/../../locales/sub1", "#{__DIR__}/../../locales/sub1/sub2", "#{__DIR__}/../../locales/sub3"]
```

**Comment by kingsleyh** [comment]
actually after further investigation this works:

`I18n.load_path += ["#{__DIR__}/../../locales/**/"`

maybe it was a typo in the documentation?

**Comment by TechMagister** [comment]
Hi kingsleyh,
You're right, I'll fix the README.
Thanks
